import os

# Constants
METRICOOL_BASE_URL = "https://app.metricool.com/api"
METRICOOL_USER_TOKEN = os.getenv("XUHZPETXIYOLBZOMPMYUBAHMUTPOPKKXZNMKYZXTIBLVUTWGDTKTJKTOODCZPYGV")
METRICOOL_USER_ID = os.getenv("2867172")
